---
title: "Rainfall data: https://grogdata.soest.hawaii.edu/" 
author: "Elmera Azadpour"
date: "06/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(ggpubr)
library(here)
```

```{r}
kuli_rain <- read.csv(here("data", "KuliRain_20210512.csv")) %>% 
  select(-X)

kuli_rain$date <- as_datetime(kuli_rain$date)

kuli_rain_tidy <- kuli_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

kuli_rain_daily <- kuli_rain_tidy %>% 
  group_by(year, month, day) %>% 
  summarise(daily_pcp = sum(rain)) %>%
  mutate(date = make_date(year, month, day)) 

kuli_rain_daily_in <- kuli_rain_daily %>% 
  mutate(daily_pcp = daily_pcp/25.4) #divide by 25.4: convert from mm to inches

ggplot(kuli_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") + 
  labs(x= "Year", y="Precipitation (mm)", title = "Kuli'ou'ou Ridge Rainfall") + 
  theme_minimal() 

kuli_plot_pcp <- ggplot(kuli_rain_daily_in, aes(date, daily_pcp)) +
  geom_line(color = "blue") + 
  labs(x= "Year", y="Precipitation (in)", title = "Kuli'ou'ou Ridge Rainfall") + 
  theme_minimal() 

kuli_plot_pcp
```

## Wailupe Rain
```{r}
wailupe_rain <- read.csv(here("data", "WailupeRain_20210512.csv"))

wailupe_rain$date <- as_datetime(wailupe_rain$date)

wailupe_rain_tidy <- wailupe_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

wailupe_rain_daily <- wailupe_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4) # converts from mm to inches

wailupe_plot_pcp <- ggplot(wailupe_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Wailupe Fire Station Rainfall") + 
  theme_minimal()

wailupe_plot_pcp
```

## Lunalilo Homes Rainfall
```{r}
lunalilo_rain <- read.csv(here("data", "LunaliloRain_20210512.csv"))

lunalilo_rain$date <- as_datetime(lunalilo_rain$date)

lunalilo_rain_tidy <- lunalilo_rain %>%
  mutate(year = year(date), 
         month = month(date),
         day = day(date),
         hour = hour(date))

lunalilo_rain_daily <- lunalilo_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4) #converting from mm to inches

lunalilo_plot_pcp <- ggplot(lunalilo_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Lunalilo Homes Rainfall") + 
  theme_minimal() 

lunalilo_plot_pcp
```

## Niu Valley BWS Rainfall
```{r}
niuvalley_rain <- read.csv(here("data", "NiuValleyRain_20210512.csv"))

niuvalley_rain$date <- as_datetime(niuvalley_rain$date)

niuvalley_rain_tidy <- niuvalley_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

niuvalley_rain_daily <- niuvalley_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4) # converts from mm to inches

niuvalley_plot_pcp <- ggplot(niuvalley_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Niu Valley BWS Rainfall") + 
  theme_minimal() 

niuvalley_plot_pcp
```

## Kuli‘ou‘ou 350 BWS Rainfall
```{r}
kuli350_rain <- read.csv(here("data", "Kuli350Rain_20210512.csv"))

kuli350_rain$date <- as_datetime(kuli350_rain$date)

kuli350_rain_tidy <- kuli350_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

kuli350_rain_daily <- kuli350_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
    mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4)

kuli350_plot_pcp <- ggplot(kuli350_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Kuli'ou'ou 350 BWS Rainfall") + 
  theme_minimal() 

kuli350_plot_pcp
```
## Alamuka Street BWS Rainfall
```{r}
alamuka_rain <- read.csv(here("data", "AlamukaRain_20210512.csv"))

alamuka_rain$date <- as_datetime(alamuka_rain$date)

alamuka_rain_tidy <- alamuka_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

alamuka_rain_daily <- alamuka_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4) #covert from mm to inches

alamuka_plot_pcp <- ggplot(alamuka_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Alamuka Street BWS Rainfall") + 
  theme_minimal() 

alamuka_plot_pcp
```

## Hawai'i Loa Ridge Rainfall
```{r}
hawaiiloa_rain <- read.csv(here("data", "HawaiiLoaRain_20210512.csv"))

hawaiiloa_rain$date <- as_datetime(hawaiiloa_rain$date)

hawaiiloa_rain_tidy <- hawaiiloa_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

hawaiiloa_rain_daily <- hawaiiloa_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4)

hawaiiloa_plot_pcp <- ggplot(hawaiiloa_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Hawai'i Loa Ridge Rainfall") + 
  theme_minimal() 

hawaiiloa_plot_pcp
```

## Wiliwilinui Ridge Rainfall
```{r}
wili_rain <- read.csv(here("data", "WiliRain_20210512.csv"))

wili_rain$date <- as_datetime(wili_rain$date)

wili_rain_tidy <- wili_rain %>% 
  mutate(year = year(date), 
         month = month(date), 
         day = day(date), 
         hour = hour(date))

wili_rain_daily <- wili_rain_tidy %>% 
  group_by(year, month,day) %>% 
  summarise(daily_pcp = sum(rain)) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  mutate(daily_pcp = daily_pcp/25.4)

wili_plot_pcp <- ggplot(wili_rain_daily, aes(date, daily_pcp)) +
  geom_line(color = "blue") +
  labs(x= "Year", y="Precipitation (in)", title = "Wiliwilinui Ridge Rainfall") + 
  theme_minimal()


wili_plot_pcp
```

## Combine Graphs
```{r}
# ggarange
all_plots <- ggarrange(wailupe_plot_pcp, kuli_plot_pcp, kuli350_plot_pcp, lunalilo_plot_pcp, niuvalley_plot_pcp, alamuka_plot_pcp, hawaiiloa_plot_pcp, wili_plot_pcp,  ncol = 2, nrow = 4, labels = "AUTO")


ggsave("all_pcp_plots.pdf", width = 12, height = 8)
```

```{r}
# compare Wiliwilnui Ridge to Kuliouou Ridge
# compare hourly

wili_rain_hourly <- wili_rain_tidy %>% 
  mutate(rain_in = rain/25.4) %>% 
  filter(year == 2021) %>% 
  filter(month == 1) %>% 
  group_by(year, month, day) %>% 
  filter(day %in% c(16,17,18,19,20))

kuli_rain_hourly <- kuli_rain_tidy %>% 
  mutate(rain_in = rain/25.4) %>% 
  filter(year == 2021) %>% 
  filter(month == 1) %>% 
  group_by(year, month, day) %>% 
  filter(day %in% c(16,17,18,19,20))

# compare the 18th
wili_rain_18 <- wili_rain_hourly %>% 
  filter(day == 18)

kuli_rain_18 <- kuli_rain_hourly %>% 
  filter(day == 18)

ggplot() +
  geom_line(data = wili_rain_18, aes(x = hour,
                                     y = rain_in)) +
  geom_line(data = kuli_rain_18, aes(x = hour,
                                     y = rain_in)) +
  theme_minimal()

# correlation plot
kuli_wili_comp <- merge(kuli_rain_18, wili_rain_18, by = "hour")

ggplot(data = kuli_wili_comp, aes(x = rain_in.x,
                                  y = rain_in.y)) +
  geom_point() +
  geom_smooth(method='lm', formula = y~x) +
  stat_regline_equation(label.x = 0.25,
                        label.y = 0.75) +
  stat_cor(label.x = 0.25,
           label.y = 0.8) +
  theme_minimal() +
  labs(x = "Kuliouou Ridge",
       y = "Wiliwilinui Ridge")
  
```

```{r}
# compare Hawaii Loa Ridge to Kuliouou Ridge
# compare hourly

hawaiiloa_rain_hourly <- hawaiiloa_rain_tidy %>% 
  mutate(rain_in = rain/25.4) %>% 
  filter(year == 2021) %>% 
  filter(month == 1) %>% 
  group_by(year, month, day) %>% 
  filter(day %in% c(16,17,18,19,20))

kuli_rain_hourly <- kuli_rain_tidy %>% 
  mutate(rain_in = rain/25.4) %>% 
  filter(year == 2021) %>% 
  filter(month == 1) %>% 
  group_by(year, month, day) %>% 
  filter(day %in% c(16,17,18,19,20))

# compare the 18th
kuli_rain_18 <- kuli_rain_hourly %>% 
  filter(day == 18)

hawaiiloa_rain_18 <- hawaiiloa_rain_hourly %>% 
  filter(day == 18)

ggplot() +
  geom_line(data = kuli_rain_18, aes(x = hour,
                                     y = rain_in,
                                     color = "blue")) +
  geom_line(data = hawaiiloa_rain_18, aes(x = hour,
                                     y = rain_in,
                                     color = "red")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Kuliouou", "Hawaii Loa")) +
  theme(legend.title = element_blank())

# correlation plot
kuli_hawaiiloa_comp <- merge(kuli_rain_18, hawaiiloa_rain_18, by = "hour")

ggplot(data = kuli_hawaiiloa_comp, aes(x = rain_in.x,
                                  y = rain_in.y)) +
  geom_point() +
  geom_smooth(method='lm', formula = y~x) +
  stat_regline_equation(label.x = 0.25,
                        label.y = 0.75) +
  stat_cor(label.x = 0.25,
           label.y = 0.8) +
  theme_minimal() +
  labs(x = "Kuliouou Ridge",
       y = "Hawaii Loa Ridge")
```

```{r}
# all three plotted together

ggplot() +
  geom_line(data = kuli_rain_18, aes(x = hour,
                                     y = rain_in,
                                     color = "blue")) +
  geom_line(data = hawaiiloa_rain_18, aes(x = hour,
                                     y = rain_in,
                                     color = "red")) +
  geom_line(data = wili_rain_18, aes(x = hour,
                                     y = rain_in,
                                     color = "orange")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red", "orange"), labels = c("Kuliouou", "Wiliwilinui", "Hawaii Loa")) +
  theme(legend.title = element_blank())
```

